{
    "env": {
      "amd": true,
      "es6": true,
      "node": true
    },
    "extends": [
      "prettier",
      "eslint:recommended"
    ],
    "ignorePatterns": [
      "src/node_modules"
    ],
    "parserOptions": {
      "ecmaFeatures": {
        "modules": true
      },
      "ecmaVersion": "2020",
      "sourceType": "module"
    },
    "rules": {}
  }
